
mode: "train"

exp_prefix: "dm"

base_dir: "results/{{exp_prefix}}"
log_dir: "log.jsonl"

checkpoint_dir: "{{base_dir}}/checkpoints"
checkpoint_file: best_model

framework:
    seed: 12345
    num_thread: 1
    num_gpu: 1

model:
    protocol: state # {state, image}
    backbone: gru # {fc, gru, lstm}
    hidden_dim: 64

data:
    protocol: state
    delta_t: 0.05
    horizon: 50
    input_dim: 6
    output_dim: 4
    batch_size: 50
    num_datapoints_per_epoch: 50
    num_traj_samples: 10
    expert_policy: random # {random, swing_up}
    policy_dir: ''
    default_init_state: [0.01, 0.01, 0.5, 0.1] # note that we are going to do init_state[2] * np.pi in the script
    image:
        cart_width: 1.0
        cart_height: 0.5
        pole_length: 1.0
        pole_thickness: 3.0
        figsize: [4, 3]
        alpha: 0.5

train:
    num_epoch: 100
    lr: 0.01
    lr_ms: [70, 90]
    save_iter: 10

test:
    gt_title: Full-Dynamics Prediction
    model_title: NN Prediction
    film: True
