
mode: "train"

exp_prefix: "dm"

base_dir: "results/{{exp_prefix}}"
log_dir: "log.jsonl"

checkpoint_dir: "{{base_dir}}/checkpoints"
checkpoint_file: 00000

framework:
    seed: 0
    num_thread: 1
    num_gpu: 1

model:
    protocol: resnet18
    batch_size: 128
    input_dim: (3, 300, 300)
    hidden_size: 512
    output_size: 6

agent:
    protocol:

train:
    num_epoch: 1
    lr: 0.1
    lr_ms: [15000, 20000]
    save_iter: 1000
